"""new accepted column for friends

Revision ID: 0c398d045aae
Revises: 6bbdf8209531
Create Date: 2022-02-07 14:21:53.195443

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0c398d045aae"
down_revision = "6bbdf8209531"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "friends",
        sa.Column("accepted", sa.Boolean(), server_default="false", nullable=False),
    )
    op.create_foreign_key(None, "friends", "users", ["friend_id"], ["id"])
    op.create_foreign_key(None, "friends", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "friends", type_="foreignkey")
    op.drop_constraint(None, "friends", type_="foreignkey")
    op.drop_column("friends", "accepted")
    # ### end Alembic commands ###
