"""new friends tables

Revision ID: 1087104f3af4
Revises: 0c398d045aae
Create Date: 2022-02-07 16:15:16.009915

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1087104f3af4"
down_revision = "0c398d045aae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "friendrequests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("friend_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["friend_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_friendrequests_friend_id"),
        "friendrequests",
        ["friend_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_friendrequests_id"), "friendrequests", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_friendrequests_user_id"), "friendrequests", ["user_id"], unique=False
    )
    op.drop_column("friends", "accepted")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "friends",
        sa.Column(
            "accepted",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index(op.f("ix_friendrequests_user_id"), table_name="friendrequests")
    op.drop_index(op.f("ix_friendrequests_id"), table_name="friendrequests")
    op.drop_index(op.f("ix_friendrequests_friend_id"), table_name="friendrequests")
    op.drop_table("friendrequests")
    # ### end Alembic commands ###
