"""test migration

Revision ID: 64cc49917136
Revises: ff67145beff1
Create Date: 2022-02-02 20:42:05.558426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64cc49917136'
down_revision = 'ff67145beff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
