"""Initial tables

Revision ID: 65dbc517b35f
Revises: 
Create Date: 2022-02-01 17:28:54.774031

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "65dbc517b35f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
