"""create Friends table

Revision ID: 6bbdf8209531
Revises: a511ff813909
Create Date: 2022-02-07 00:20:44.365375

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "6bbdf8209531"
down_revision = "a511ff813909"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "friends",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True, foreign_key="users.id"),
        sa.Column("friend_id", sa.Integer(), nullable=True, foreign_key="users.id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_friends_friend_id"), "friends", ["friend_id"], unique=False
    )
    op.create_index(op.f("ix_friends_id"), "friends", ["id"], unique=False)
    op.create_index(op.f("ix_friends_user_id"), "friends", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_friends_user_id"), table_name="friends")
    op.drop_index(op.f("ix_friends_id"), table_name="friends")
    op.drop_index(op.f("ix_friends_friend_id"), table_name="friends")
    op.drop_table("friends")
    # ### end Alembic commands ###
