"""changed int to uuid

Revision ID: 70591ff7ac5f
Revises: e98971a30fd5
Create Date: 2022-02-05 16:14:14.534388

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "70591ff7ac5f"
down_revision = "e98971a30fd5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
