"""autoincrement for user table id column

Revision ID: e956e50dc089
Revises: 64cc49917136
Create Date: 2022-02-04 21:05:51.664170

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e956e50dc089"
down_revision = "64cc49917136"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
