"""changed int to uuid

Revision ID: e98971a30fd5
Revises: 6089078909cd
Create Date: 2022-02-05 16:09:36.863975

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e98971a30fd5"
down_revision = "6089078909cd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
